version: '3'

services:
  database:
    image: postgres:latest
    ports: 
     - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  testDatabase:
    image: postgres:latest
    ports: 
     - "6000:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - test_db:/var/lib/postgresql/data

volumes:
  db:
  test_db: