version: '3'

services:
  database:
    image: postgres:latest
    ports: 
     - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  db: